### ISSUE TITLE
Changing the plug name causes homebridge to not be able to connect to the devices.

### ISSUE THREAD

**Issue by LaChrome** [AlakhaiVaynard/homebridge-vesync#3]
Steps to reproduce:

1. Configure homebridge with the homebridge-vesync plugin, and connect to account in the config.json.
2. Start homebridge. Devices connected and working in HomeKit.
3. From VeSync app, change the details of the plugs (change the name of the plug in the VeSync app settings).
 - Homebridge and HomeKit are now no longer able to connect to the devices.
 - Restarting Homebridge doesn't resolve the issue. 

Following error is generated:
(node:71530) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'status' of undefined
(node:71530) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:71530) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'status' of undefined

Restarting Homebridge doesn't resolve the issue.

Remaming the devices back to the original names fixes the issue.

**Comment by bbernstein** [comment]
I am seeing the same issue. These are great inexpensive outlets and as I start setting them up and finding good naming conventions, we need to be able to change names easily.

**Comment by bbernstein** [comment]
This solves it for me. It's probably easies for a contributor to make this change. It simply checks if device is undefined and removes it if it is. Then next cycle, it picks up the new name:

```
diff --git a/index.js b/index.js
index 1d131c2..ba2d3f4 100644
--- a/index.js
+++ b/index.js
@@ -192,9 +192,15 @@ VeseyncPlugPlatform.prototype.getPowerState = function(thisPlug, callback) {
         }).then( devices => {
           return devices.find( (device) => { return device.name.includes(thisPlug.name); });
         }).then( (device) => {
-            thisPlug.status = device.status;
-            if (this.debug) this.log("Discovery complete");
-            callback(null, device.status == 'open');
+            if (typeof device === 'undefined') {
+                if (this.debug) this.log("Removing undefined device", thisPlug.name);
+                removeAccessory(thisPlug)
+            }
+            else {
+                thisPlug.status = device.status;
+                if (this.debug) this.log("Discovery complete");
+                callback(null, device.status == 'open');
+            }
         });
     } else {
         callback(new Error("Device not found"));
```

**Comment by AlakhaiVaynard** [comment]
Sorry for ghosting on this for a while here everyone, been hectic for me - and I was using my outlets around Christmas but not as much recently, so slipped my mind.  I'll get this merged in here soon, thanks for doing the legwork.

**Comment by KaidenR** [comment]
Just wanted to say thanks for this fix. I ran into the same bug, came here, and realized you had already fixed it. Nicely done.
